FROM node:22-alpine

WORKDIR /app

# Enable Corepack for Yarn 4
RUN corepack enable

# Copy everything
COPY . .

# Install dependencies
RUN yarn install

# Build TypeScript
RUN yarn build

# Expose GraphQL port
EXPOSE 4001

# Start GraphQL Server
CMD ["node", "dist/graphql/start-graphql-server.js"]

