# Railway Configuration for Clear AI v2
# Docs: https://docs.railway.com/reference/config-as-code

# Default configuration for Wasteer API
# This will be used unless overridden in Railway UI per service

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.graphql"

[deploy]
startCommand = "node dist/graphql/start-graphql-server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/graphql"
healthcheckTimeout = 300
