/**
 * MongoDB Plan Model
 * Schema for storing execution plans generated by the Planner Agent
 */

import mongoose, { Document, Schema } from 'mongoose';
import { Plan } from '../../shared/types/agent.js';

export interface IPlanDocument extends Document {
  requestId: string;
  query: string;
  plan: Plan;
  context?: any;
  status: 'pending' | 'executing' | 'completed' | 'failed';
  createdAt: Date;
  updatedAt: Date;
}

const planSchema = new Schema<IPlanDocument>({
  requestId: {
    type: String,
    required: true,
    unique: true,
    index: true
  },
  query: {
    type: String,
    required: true
  },
  plan: {
    type: Schema.Types.Mixed,
    required: true
  },
  context: {
    type: Schema.Types.Mixed,
    default: null
  },
  status: {
    type: String,
    enum: ['pending', 'executing', 'completed', 'failed'],
    default: 'pending'
  },
  createdAt: {
    type: Date,
    default: Date.now,
    index: true
  },
  updatedAt: {
    type: Date,
    default: Date.now
  }
}, {
  timestamps: true
});

// Indexes for better query performance
planSchema.index({ requestId: 1 });
planSchema.index({ createdAt: -1 });
planSchema.index({ status: 1 });
planSchema.index({ createdAt: -1, status: 1 });

export const PlanModel = mongoose.model<IPlanDocument>('Plan', planSchema);
