/**
 * Agent-related type definitions
 * Core types used by Planner, Executor, Analyzer, and Summarizer agents
 */

/**
 * Plan generated by Planner Agent
 */
export interface Plan {
  steps: PlanStep[];
  metadata?: PlanMetadata | undefined;
}

export interface PlanStep {
  tool: string;
  params: Record<string, any>;
  depends_on?: number[] | undefined; // Indices of steps this depends on
  parallel?: boolean | undefined; // Can be run in parallel
  optional?: boolean | undefined; // Step can fail without stopping execution
  retry_count?: number | undefined; // Number of retries attempted
  timeout?: number | undefined; // Step timeout in milliseconds
}

export interface PlanMetadata {
  query: string;
  timestamp: string;
  estimated_duration_ms?: number | undefined;
  intent?: Intent | undefined; // Recognized intent from query
  confidence?: number | undefined; // Confidence score for plan quality
}

export interface Intent {
  type: 'CREATE' | 'READ' | 'UPDATE' | 'DELETE' | 'ANALYZE' | 'MONITOR';
  entities: string[];
  operations: string[];
  confidence: number; // 0-1
}

/**
 * Tool execution result from Executor Agent
 */
export interface ToolResult {
  success: boolean;
  tool: string;
  data?: any;
  error?: ErrorDetails;
  metadata: ToolResultMetadata;
  step_index?: number | undefined; // Index of step in plan
  resolved_params?: Record<string, any> | undefined; // Parameters after reference resolution
}

export interface ToolResultMetadata {
  executionTime: number;
  timestamp: string;
  retries?: number;
}

export interface ErrorDetails {
  code: string;
  message: string;
  details?: any;
}

/**
 * Analysis from Analyzer Agent
 */
export interface Analysis {
  summary: string;
  insights: Insight[];
  entities: Entity[];
  anomalies: Anomaly[];
  metadata: AnalysisMetadata;
  reasoning_trace?: ReasoningStep[]; // Chain-of-thought reasoning steps
  validation_result?: ValidationResult; // Self-critique validation
}

export interface Insight {
  type: 'trend' | 'pattern' | 'correlation' | 'comparison' | 'contamination_pattern' | 'capacity_risk' | 'data_quality' | 'compliance_risk' | 'operational_efficiency';
  description: string;
  confidence: number; // 0-1
  supporting_data: any[];
}

export interface Entity {
  id: string;
  type: string;
  name: string;
  attributes: Record<string, any>;
  relationships?: Relationship[];
}

export interface Relationship {
  type: string;
  targetEntityId: string;
  strength?: string;
}

export interface Anomaly {
  type: 'outlier' | 'unexpected' | 'missing' | 'threshold_exceeded' | 'data_quality' | 'data_contradiction' | 'missing_relationship' | 'capacity_exceeded' | 'capacity_warning' | 'missing_contact';
  description: string;
  severity: 'low' | 'medium' | 'high' | 'critical';
  affected_entities: string[];
  data: any;
}

export interface AnalysisMetadata {
  tool_results_count: number;
  successful_results?: number;
  failed_results?: number;
  analysis_time_ms: number;
}

/**
 * Final response from Summarizer Agent
 */
export interface FinalResponse {
  message: string;
  tools_used: string[];
  data?: any;
  analysis?: Analysis;
  metadata: ResponseMetadata;
}

export interface ResponseMetadata {
  request_id: string;
  total_duration_ms: number;
  timestamp: string;
  error?: boolean;
  reasoning_trace?: ReasoningStep[]; // Chain-of-thought reasoning steps
  validation_result?: ValidationResult; // Self-critique validation
}

/**
 * Chain-of-thought reasoning step
 */
export interface ReasoningStep {
  step_number: number;
  reasoning_type: 'observation' | 'correlation' | 'hypothesis' | 'validation' | 'conclusion' | 'extraction' | 'prioritization' | 'structuring' | 'composition' | 'refinement';
  description: string;
  input: any;
  output: any;
  confidence?: number;
  timestamp: string;
}

/**
 * Self-critique validation result
 */
export interface ValidationResult {
  is_valid: boolean;
  quality_score: number; // 0-1
  issues: ValidationIssue[];
  recommendations: string[];
  confidence: number; // 0-1
  timestamp: string;
}

export interface ValidationIssue {
  type: 'relevance' | 'clarity' | 'actionability' | 'completeness' | 'accuracy' | 'tone';
  severity: 'low' | 'medium' | 'high' | 'critical';
  description: string;
  suggestion: string;
}

