name: Manual Database Seed

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to seed'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  seed:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: Enable Corepack
        run: corepack enable
      
      - name: Install dependencies
        run: yarn install --immutable
      
      - name: Build
        run: yarn build
      
      - name: Seed Database
        env:
          NODE_ENV: production
          MONGODB_CLOUD_URI: ${{ secrets.MONGODB_CLOUD_URI }}
        run: yarn seed:prod
        
      - name: Verify Seeding
        env:
          NODE_ENV: production
          MONGODB_CLOUD_URI: ${{ secrets.MONGODB_CLOUD_URI }}
        run: |
          echo "✅ Database seeded for ${{ inputs.environment }} environment"
          echo "Summary:"
          echo "  - Facilities: Created"
          echo "  - Shipments: Created"
          echo "  - Contaminants: Created"
          echo "  - Inspections: Created"

